// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZakirPro.Data;

#nullable disable

namespace ZakirPro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZakirPro.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Lecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GoogleDriveLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeacherSubjectStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeacherSubjectStageId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.StudentTeacherSubjectStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherSubjectStageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherSubjectStageId");

                    b.HasIndex("StudentId", "TeacherSubjectStageId")
                        .IsUnique();

                    b.ToTable("StudentTeacherSubjectStages");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.TeacherSubjectStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId", "StageId")
                        .IsUnique();

                    b.ToTable("TeacherSubjectStages");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("ZakirPro.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Assistant", b =>
                {
                    b.HasBaseType("ZakirPro.Domain.Entities.User");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasIndex("TeacherId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Gender")
                                .HasColumnName("Assistant_Gender");
                        });

                    b.HasDiscriminator().HasValue("Assistant");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("ZakirPro.Domain.Entities.User");

                    b.Property<string>("ActivationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.SuperAdminUser", b =>
                {
                    b.HasBaseType("ZakirPro.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("SuperAdmin");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Teacher", b =>
                {
                    b.HasBaseType("ZakirPro.Domain.Entities.User");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Lecture", b =>
                {
                    b.HasOne("ZakirPro.Domain.Entities.TeacherSubjectStage", "TeacherSubjectStage")
                        .WithMany("Lectures")
                        .HasForeignKey("TeacherSubjectStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherSubjectStage");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.StudentTeacherSubjectStage", b =>
                {
                    b.HasOne("ZakirPro.Domain.Entities.Student", "Student")
                        .WithMany("StudentTeacherLinks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZakirPro.Domain.Entities.TeacherSubjectStage", "TeacherSubjectStage")
                        .WithMany("StudentLinks")
                        .HasForeignKey("TeacherSubjectStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TeacherSubjectStage");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.TeacherSubjectStage", b =>
                {
                    b.HasOne("ZakirPro.Domain.Entities.Stage", "Stage")
                        .WithMany("TeacherSubjectStages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZakirPro.Domain.Entities.Subject", "Subject")
                        .WithMany("TeacherSubjectStages")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZakirPro.Domain.Entities.Teacher", "Teacher")
                        .WithMany("TeacherSubjectStages")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Assistant", b =>
                {
                    b.HasOne("ZakirPro.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Assistants")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Stage", b =>
                {
                    b.Navigation("TeacherSubjectStages");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Subject", b =>
                {
                    b.Navigation("TeacherSubjectStages");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.TeacherSubjectStage", b =>
                {
                    b.Navigation("Lectures");

                    b.Navigation("StudentLinks");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentTeacherLinks");
                });

            modelBuilder.Entity("ZakirPro.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Assistants");

                    b.Navigation("TeacherSubjectStages");
                });
#pragma warning restore 612, 618
        }
    }
}
